### PR TITLE
Reorganize TIBCO Messaging repo by component

### PR DESCRIPTION
**Pull request by mcarway-arch**
Update to the layout of the repo to organize by component of TIBCO Messaging. This includes an update to the top level readme to reflect how the repo is laid out after this change

### CODE REVIEW

**Review by rselph-tibco — CHANGES_REQUESTED** [review]
Any `.idea/` directory should be removed, and that name should be added to .gitignore.  These directories come from JetBrains IDEs.

**Review by rselph-tibco — COMMENTED** [review]
Two things we might create issues for: Review all the go directories for correct go.mod files, and convert any remaining README.txt files to README.md.

**Comment by mcarway-arch** [comment]
Removed the .idea directories. I plan to do some other clean up task along the lines of what you indicated in the other comment.

**Review by rselph-tibco — APPROVED** [review]
Looks good.

**Pull request merged**
